---
title: "Code details"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## File *simulations.r*

The variable `options_model` can assume values 1,2, or 3, and corresponds to the null space *type* 1,2, or 3, respectively, as defined in the paper. It defines how to generate the basis matrix and which covariates are included into the model to fit, as described in the table below. 

To start with, `p_formula` is a one-sided formula that specifies how  null-space of the principal splines is constructed. As in the `lm()` function, the intercept is always included unless otherwise stated. The basis matrix is `B = cbind(U, E)`, where the vectors in `U` span the nullspace, and `E` is the matrix of eigenvectors corresponding to positive eigenvalues of the bending energy matrix. The following table specifies how `p_formula` and `options_model` are related. Also, `~coords` is a shortcut used here to indicate `~lngcoords+latcoords`, i.e. the names of the 2 columns of the `coords` dataframe object. `q` represents the dimension of the nullspace and is such that `ncol(E) = n0-q`, where `n0` is the number of sampled locations.

| `options model` | `p_formula`  |  `U` | `q` |
|:---:|:---:|:---:|:---:|
| 1 |  `~coords` | `cbind(1, coords)`  | 3  |
| 2 | `~x+coords`  | `cbind(1, x, coords)`  | 4  |
| 3 | `~x`  | `cbind(1, x)`  | 2  |


`reg_formula` is a one-sided formula that specifies how to build the design matrix in the semi-parametric regression model. This design matrix is the "full" one, i.e. with all the observed covariates and bases. Its first two columns are always the intercept and the exposure. The full matrix is then split into two sub-matrices: a first part with the covariates that we always want to include in the model fit (e.g., intercept and exposure), denoted as `xb` in the source code, and a second part where we assume the spike-and-slab prior structure on the respective coefficients (indicated by `B2` in the source code). The logical vector `includevars` specifies how the split is done. Specifically, for each element *i* in the vector:

- if `includevars[i] == TRUE`, the corresponding column of the full design matrix is part of `xb`

- if `includevars[i] == FALSE`, the corresponding column of the full design matrix is part of `B2`

In the following table, `len=length(includevars)` indicates the number of elements in `includevars`, i.e. the number of columns of the full design matrix, and `s=sum(includevars)` defines how many columns `xb` will have (`s>=2` since intercept and exposure are always included).


| `options model` | `len`  | `s`  | `reg_formula`  | `xb` | `B2` |
|:--:|:-:|:-:|:--:|:---:|:---:|
| 1 | `n0+1`  | 2  | `~x+coords+B`  | `cbind(1,x)`  | `cbind(coords, E)`  |
| 2 | `n0`  | 4  | `~x+coords+B`  | `cbind(1,x,coords)`  | `E`  |
| 3 | `n0`  | 2  | `~x+B` | `cbind(1,x)`  | `E`  |



## File *setting.xslx*

Here, the meaning of the names of the columns of this file is explained.

|  Excel file  | Notation of the paper |
|:-:|:-:|
|  sim |  configuration number |
|  cov_func |  covariance function |
|  smooth_param |  smoothness parameter (e.g. of Matérn) |
|  range1 |  $\phi_x$ |
| range2  | $\phi_w$  |
| delta  |  $\delta$ |
| sigma_1  |  $\sigma_z^2$ |
| sigma_2  |  $\sigma_w^2$ |
| tau  |  $\sigma_y^2$ |

For the spatial covariance function, the avaliable options are `"matern", "exponential", "gaussian", "spherical", "powered.exponential"`.


## File *data_generate.r*

`type` defines the data generating mechanism, and the options are:

- `'conditional'`: this option simulates data conditionally on the exposure, that is using the distributions of $\mathbf{W|X}$ and $\mathbf{Y|X}$, with the parameters set at the values defined by the j-th configuration in *setting.xslx* (i.e., after importing the Excel file in R, select the j-th row to see the values of the parameters).

- `'RelBias_deltafixed'`: this is the data generating mechanism described in Section 5 of the paper. The relative bias (wrt OLS) is fixed throughout the replicates. Also, the correlation parameter ($\delta$) is fixed as well at the value defined by the j-th configuration. $\sigma_w^2$ is allowed to vary across replicates, and the values in the Excel file are overridden.

- `'RelBias_sigma2fixed'`: the relative bias (wrt OLS) is fixed throughout the replicates. Also, the partial sill of the unmeasured confounder ($\sigma_w^2$) is fixed as well at the level defined by the j-th configuration in *setting.xslx*. $\delta$ is allowed to vary across replicates, and the values in the Excel file are overridden.





<!-- # References -->

<!-- 1. Guan, Y., Page, G. L., Reich, B. J., Ventrucci, M., & Yang, S. (2020). A spectral adjustment for spatial confounding. [ArXiv:2012.11767](http://arxiv.org/abs/2012.11767). -->
<!-- 2. Marques I, Kneib T. (2022) Discussion on “Spatial+: A novel approach to spatial confounding” by Emiko Dupont, Simon N. Wood, and Nicole H. Augustin. Biometrics. 1–5. [doi](https://doi.org/10.1111/biom.13650). -->
<!-- 3. Schmidt, A.M. (2022) Discussion on “Spatial+: A novel approach to spatial confounding” by Emiko Dupont, Simon N. Wood, and Nicole H. Augustin. Biometrics, 00, 1–5. [doi](https://doi.org/10.1111/biom.13654) -->